bundle cli
lovelysystems/lovely-kafka-backup pull request #5
Opened 2023-09-07 08:35 UTC by Lukas-Kaufmann

2023-09-07 08:38 UTC, Lukas-Kaufmann commented on README.md
> -| Option name      | Short option | Required                                    | Format              | Description
reordered parameters so that required ones are at top

2023-09-07 08:59 UTC, mikethebeer requested changes

2023-09-07 08:59 UTC, mikethebeer commented on docker/Dockerfile
> +COPY backup-cli-libs/ /usr/share/java/backup-cli/
I would not move it to the `/usr/share/java/` dir since this is used by kafka-connect. I would rather move it to `/opt/`

2023-09-07 08:59 UTC, mikethebeer commented on docker/entrypoint.sh
> +  JAR_NAME=$(ls /usr/share/java/backup-cli/cli*.jar | head -1)
This feels a bit hacky. I would rather rename the jar when it gets built or even better would be to create a native image using GraalVM. In this case I'd prefer the later. PicoCLI supports it as well:

https://picocli.info/#_graalvm_native_image

and the Gradle Plugin is here https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html

2023-09-07 08:59 UTC, mikethebeer commented on localdev/docker-compose.yml
> +      KAFKA_CFG_ADVERTISED_LISTENERS: 'DOCKER://kafka:29092,HOST://localhost:9092,DOCKERCLI://host.docker.internal:9093'
:thinking: I think if you attach the backup cli container to the host network this configuration is obsolete.

e.g. `docker run --network host lovelysystems/lovely-kafka-backup:dev restore ...`

2023-09-07 08:59 UTC, mikethebeer commented on localdev/docker-compose.yml
> +      KAFKA_CFG_ADVERTISED_LISTENERS: 'DOCKER://kafka:29092,HOST://localhost:9092,DOCKERCLI://host.docker.internal:9093'
Use this as an example

2023-09-07 08:59 UTC, mikethebeer commented on build.gradle.kts
> +            into("backup-cli-libs")
you could rename the built jar here

2023-09-08 09:27 UTC, mikethebeer approved these changes

2023-09-08 09:29 UTC, merged